interface PipelineYamlPreviewProps {
  yaml: string;
}

export function PipelineYamlPreview({ yaml }: PipelineYamlPreviewProps) {
  return (
    <section className="panel">
      <div className="panel-heading">
        <h2>YAML Preview</h2>
        <span className="muted">Generated by backend validation/save model</span>
      </div>
      <pre className="json-preview yaml-preview">{yaml || "Validate the draft to generate YAML preview."}</pre>
    </section>
  );
}
