workspaces:
- id: smoke
  name: Smoke Test Workspace
  provider: s3
  bucket: steos-s3-data
  workspace_prefix: beehive-smoke/test_workflow
  region: ru-1
  endpoint: https://s3.ru-1.storage.selcloud.ru
  workdir_path: /tmp/beehive-web-workspaces/smoke
  pipeline_path: /tmp/beehive-web-workspaces/smoke/pipeline.yaml
  database_path: /tmp/beehive-web-workspaces/smoke/app.db
  is_archived: false
  created_at: null
  updated_at: null
  archived_at: null
- id: pilot_test
  name: pilot_test
  provider: s3
  bucket: steos-s3-data
  workspace_prefix: pilot
  region: ru-1
  endpoint: https://s3.ru-1.storage.selcloud.ru
  workdir_path: /tmp/beehive-web-workspaces/pilot_test
  pipeline_path: /tmp/beehive-web-workspaces/pilot_test/pipeline.yaml
  database_path: /tmp/beehive-web-workspaces/pilot_test/app.db
  is_archived: false
  created_at: 2026-05-14T09:14:33.666896620+00:00
  updated_at: 2026-05-14T09:14:33.666896620+00:00
  archived_at: null
- id: new_dir
  name: new_dir
  provider: s3
  bucket: steos-s3-data
  workspace_prefix: new_dir
  region: ru-1
  endpoint: https://s3.ru-1.storage.selcloud.ru
  workdir_path: /tmp/beehive-web-workspaces/new_dir
  pipeline_path: /tmp/beehive-web-workspaces/new_dir/pipeline.yaml
  database_path: /tmp/beehive-web-workspaces/new_dir/app.db
  is_archived: true
  created_at: 2026-05-14T10:31:08.379561222+00:00
  updated_at: 2026-05-14T12:34:43.510341695+00:00
  archived_at: 2026-05-14T12:34:43.510341695+00:00
- id: mvbm
  name: mvbm
  provider: s3
  bucket: steos-s3-data
  workspace_prefix: mvbm
  region: ru-1
  endpoint: https://s3.ru-1.storage.selcloud.ru
  workdir_path: /tmp/beehive-web-workspaces/mvbm
  pipeline_path: /tmp/beehive-web-workspaces/mvbm/pipeline.yaml
  database_path: /tmp/beehive-web-workspaces/mvbm/app.db
  is_archived: false
  created_at: 2026-05-14T11:51:16.339320737+00:00
  updated_at: 2026-05-14T11:51:16.339320737+00:00
  archived_at: null
- id: full_test
  name: full_test
  provider: s3
  bucket: steos-s3-data
  workspace_prefix: full_test
  region: ru-1
  endpoint: https://s3.ru-1.storage.selcloud.ru
  workdir_path: /tmp/beehive-web-workspaces/full_test
  pipeline_path: /tmp/beehive-web-workspaces/full_test/pipeline.yaml
  database_path: /tmp/beehive-web-workspaces/full_test/app.db
  is_archived: false
  created_at: 2026-05-14T12:34:56.540000543+00:00
  updated_at: 2026-05-14T13:00:08.497269341+00:00
  archived_at: null
- id: test_run_1
  name: test_run_1
  provider: s3
  bucket: steos-s3-data
  workspace_prefix: test_run_1
  region: ru-1
  endpoint: https://s3.ru-1.storage.selcloud.ru
  workdir_path: /tmp/beehive-web-workspaces/test_run_1
  pipeline_path: /tmp/beehive-web-workspaces/test_run_1/pipeline.yaml
  database_path: /tmp/beehive-web-workspaces/test_run_1/app.db
  is_archived: false
  created_at: 2026-05-15T12:02:48.656991367+00:00
  updated_at: 2026-05-15T12:02:48.656991367+00:00
  archived_at: null
